[package]
edition = "2018"
build = "./common/build/build.rs"
name = "dht"
version = "0.0.1"
description = "DHT protocol library"

[dependencies]
arrayref = "0.3.5"
async-trait = "0.1.22"
base64 = "0.11.0"
failure = "0.1.6"
hex = "^0"
log = "0.4.8"
rand = "0.7.2"
sha2 = "0.8.0"
tokio = { version = "0.2.5", features = ["rt-threaded", "stream", "tcp", "udp"] }

adnl = { git = "https://github.com/tonlabs/ton-labs-adnl.git", features = ["node"] }
overlay = { git = "https://github.com/tonlabs/ton-labs-overlay.git" }
ton_api = { git = "https://github.com/tonlabs/ton-labs-tl.git", package = "ton_api" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }
lockfree = { git = "https://github.com/tonlabs/lockfree.git" }

[dev-dependencies]
ed25519 = "1.0.1"
ed25519-dalek = "1.0.0-pre.4"
external-ip = "1.0.0"
log4rs = "0.8.3"
serde_json = "1.0.41"



