[package]
build = './common/build/build.rs'
description = 'DHT protocol library'
edition = '2018'
name = 'dht'
resolver = '2'
version = '0.5.75'

[workspace]


[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
hex = '0.4'
log = '0.4'
rand = '0.8'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl.git', tag = '0.7.78' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto.git', tag = '0.1.38' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay.git', tag = '0.6.62' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl.git', package = 'ton_api', tag = '0.2.132' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.4' }

[features]
telemetry = [ 'adnl/telemetry', 'overlay/telemetry' ]

